### PR TITLE
Fix \ for Dual

### LINKED ISSUE #235: TypeError with `\` using BigFloat
This MWE should explain this issue enough
```julia
a = rand(2, 2)
b=[SparseConnectivityTracer.Dual{BigFloat, SparseConnectivityTracer.GradientTracer{SparseConnectivityTracer.IndexSetGradientPattern{Int64, BitSet}}}(big(1.5707963267948965579989817342720925807952880859375), SparseConnectivityTracer.GradientTracer{SparseConnectivityTracer.IndexSetGradientPattern{Int64, BitSet}}(SparseConnectivityTracer.IndexSetGradientPattern{Int64, BitSet}(BitSet([181])), false))
        SparseConnectivityTracer.Dual{BigFloat, SparseConnectivityTracer.GradientTracer{SparseConnectivityTracer.IndexSetGradientPattern{Int64, BitSet}}}(big(1.5707963267948965579989817342720925807952880859375), SparseConnectivityTracer.GradientTracer{SparseConnectivityTracer.IndexSetGradientPattern{Int64, BitSet}}(SparseConnectivityTracer.IndexSetGradientPattern{Int64, BitSet}(BitSet([182])), false))]
a\b
```
Stacktrace
```julia
ERROR: TypeError: in typeassert, expected SparseConnectivityTracer.Dual{BigFloat, SparseConnectivityTracer.GradientTracer{SparseConnectivityTracer.IndexSetGradientPattern{Int64, BitSet}}}, got a value of type SparseConnectivityTracer.Dual{Float64, SparseConnectivityTracer.GradientTracer{SparseConnectivityTracer.IndexSetGradientPattern{Int64, BitSet}}}
Stacktrace:
  [1] setindex!(A::Memory{SparseConnectivityTracer.Dual{BigFloat, SparseConnectivityTracer.GradientTracer{SparseConnectivityTracer.IndexSetGradientPattern{…}}}}, x::Float64, i1::Int64)
    @ Base ./genericmemory.jl:234
  [2] unsafe_copyto!(dest::Memory{SparseConnectivityTracer.Dual{BigFloat, SparseConnectivityTracer.GradientTracer{…}}}, doffs::Int64, src::Memory{Float64}, soffs::Int64, n::Int64)
    @ Base ./genericmemory.jl:144
  [3] unsafe_copyto!
    @ ./genericmemory.jl:124 [inlined]
  [4] _copyto_impl!
    @ ./array.jl:308 [inlined]
  [5] copyto!
    @ ./array.jl:294 [inlined]
  [6] copyto!
    @ ./array.jl:319 [inlined]
  [7] copyto_axcheck!
    @ ./abstractarray.jl:1167 [inlined]
  [8] AbstractMatrix{SparseConnectivityTracer.Dual{BigFloat, SparseConnectivityTracer.GradientTracer{SparseConnectivityTracer.IndexSetGradientPattern{…}}}}(A::Matrix{Float64})
    @ Base ./array.jl:616
  [9] convert
    @ ./abstractarray.jl:18 [inlined]
 [10] LU
    @ ~/.julia/juliaup/julia-1.11.1+0.aarch64.apple.darwin14/share/julia/stdlib/v1.11/LinearAlgebra/src/lu.jl:361 [inlined]
 [11] Factorization
    @ ~/.julia/juliaup/julia-1.11.1+0.aarch64.apple.darwin14/share/julia/stdlib/v1.11/LinearAlgebra/src/lu.jl:366 [inlined]
 [12] ldiv(F::LinearAlgebra.LU{Float64, Matrix{Float64}, Vector{Int64}}, B::Vector{SparseConnectivityTracer.Dual{BigFloat, SparseConnectivityTracer.GradientTracer{…}}})
    @ LinearAlgebra ~/.julia/juliaup/julia-1.11.1+0.aarch64.apple.darwin14/share/julia/stdlib/v1.11/LinearAlgebra/src/LinearAlgebra.jl:643
 [13] \
    @ ~/.julia/juliaup/julia-1.11.1+0.aarch64.apple.darwin14/share/julia/stdlib/v1.11/LinearAlgebra/src/LinearAlgebra.jl:631 [inlined]
 [14] \(A::Matrix{Float64}, B::Vector{SparseConnectivityTracer.Dual{BigFloat, SparseConnectivityTracer.GradientTracer{SparseConnectivityTracer.IndexSetGradientPattern{…}}}})
    @ LinearAlgebra ~/.julia/juliaup/julia-1.11.1+0.aarch64.apple.darwin14/share/julia/stdlib/v1.11/LinearAlgebra/src/generic.jl:1132
 [15] top-level scope
    @ REPL[47]:1
Some type information was truncated. Use `show(err)` to see complete types.
```

### PR DESCRIPTION
**Pull request by ErikQQY**
Fix: #235 

I am not sure what the tests should be or where they should be placed, but the issue with the MWE is resolved with this PR

### CODE REVIEW

**Comment by ErikQQY** [comment]
@adrhill Can we get a patch with this PR? It's kind of blocking https://github.com/SciML/BoundaryValueDiffEq.jl/pull/291

**Review by adrhill — CHANGES_REQUESTED** [review]
Sorry for the delay, we're in midst of a paper rebuttal/revision!

File: src/overloads/arrays.jl [hunk 1]
```diff
@@ -187,6 +187,22 @@ function LinearAlgebra.logabsdet(A::AbstractMatrix{D}) where {D<:Dual}
...
 end
+function LinearAlgebra.:\(A::AbstractMatrix{D}, B::AbstractVector) where {D<:Dual}
+    primals, tracers = split_dual_array(A)
+    p = primals \ B
+    t = tracers \ B
+    return D.(p, t)
+end
+function LinearAlgebra.:\(A::AbstractMatrix, B::AbstractVector{D}) where {D<:Dual}
+    return D.(A) \ B
+end
```
[the remark this answers is not in the document]
Comment (adrhill) [reply src/overloads/arrays.jl:198]: I'd suggest using the same approach as in the other two function, but call `Dual` instead of `D`.

File: src/overloads/arrays.jl [hunk 2]
```diff
@@ -187,6 +187,22 @@ function LinearAlgebra.logabsdet(A::AbstractMatrix{D}) where {D<:Dual}
     t1, t2 = LinearAlgebra.logabsdet(tracers)
     return (D(p1, t1), D(p2, t2))
 end
+function LinearAlgebra.:\(A::AbstractMatrix{D}, B::AbstractVector) where {D<:Dual}
+    primals, tracers = split_dual_array(A)
+    p = primals \ B
+    t = tracers \ B
+    return D.(p, t)
```
Comment (adrhill) [inline src/overloads/arrays.jl:194]: These should probably also say `Dual` instead of `D`, as the primal type might be promoted.

File: src/overloads/arrays.jl [hunk 3]
```diff
@@ -187,6 +187,22 @@ function LinearAlgebra.logabsdet(A::AbstractMatrix{D}) where {D<:Dual}
...
+end
+function LinearAlgebra.:\(A::AbstractMatrix, B::AbstractVector{D}) where {D<:Dual}
+    return D.(A) \ B
+end
+function LinearAlgebra.:\(A::AbstractMatrix{D}, B::AbstractVector{D}) where {D<:Dual}
```
Comment (adrhill) [inline src/overloads/arrays.jl:199]: Use `D1` and `D2` to support different primal types in the duals.

File: src/overloads/arrays.jl [hunk 4]
```diff
@@ -187,6 +187,22 @@ function LinearAlgebra.logabsdet(A::AbstractMatrix{D}) where {D<:Dual}
...
+    A_primals, A_tracers = split_dual_array(A)
+    B_primals, B_tracers = split_dual_array(B)
+    p = A_primals \ B_primals
+    t = A_tracers \ B_tracers
+    return D.(p, t)
```
Comment (adrhill) [inline src/overloads/arrays.jl:204]: These should probably also say `Dual` instead of `D`, as the primal type might be promoted.

**Review by adrhill — CHANGES_REQUESTED** [review]

File: src/overloads/arrays.jl (hunk 1 above)
[the remark this answers is not in the document]
Comment (ErikQQY) [reply src/overloads/arrays.jl:198]: Yeah, we should use the same approach as in the other functions, but that would lead to another weird issue. Here is an MWE:

```julia
S = BitSet
P = IndexSetGradientPattern{Int,S}
TG = GradientTracer{P}

# Utilities for quick testing
idx2set(is) = S(is)
idx2set(r::AbstractRange) = idx2set(collect(r))
idx2tracer(is) = TG(P(idx2set(is)))

t1 = idx2tracer([1, 3, 4])
t2 = idx2tracer([2, 4])
t3 = idx2tracer([8, 9])
t4 = idx2tracer([8, 9])
A = [t1 t2; t3 t4]
s_out = idx2set([1, 2, 3, 4, 8, 9])

x = rand(2)
b = A \ x # Matrix{GradientTracer}\Vector{Float64} working

A = rand(2, 2)
x = [t1; t2]
b = A \ x # Matrix{Float64}\Vector{GradientTracer} failing
```
Stacktrace:
```julia
ERROR: Function iszero requires primal value(s).
A dual-number tracer for local sparsity detection can be used via `TracerLocalSparsityDetector`.
```

I believe that is not intended right?

**Comment by ErikQQY** [comment]
Test failures seem not related

**Comment by ErikQQY** [comment]
Bump @adrhill

File: src/overloads/arrays.jl (hunk 1 above)
[the remark this answers is not in the document]
Comment (adrhill) [reply src/overloads/arrays.jl:198]: That issue also needs to be fixed for global tracers by adding a `LinearAlgebra.:\(A::AbstractMatrix{<:AbstractTracer}, B::AbstractVector)`. Then my proposed approach for duals will work.

**Review by adrhill — CHANGES_REQUESTED** [review]

File: src/overloads/arrays.jl (hunk 1 above)
[the remark this answers is not in the document]
Comment (adrhill) [reply src/overloads/arrays.jl:198]: In summary, something along the lines of 
```Julia
function LinearAlgebra.:\(A::AbstractMatrix, B::AbstractVector{D}) where {D<:Dual}
     primals, tracers = split_dual_array(A)
     p = primals \ B
     t = tracers \ B
     return Dual.(p, t)
 end
 
 function LinearAlgebra.:\(A::AbstractMatrix, B::AbstractVector{T}) where {D<:AbstractTracer}
     return ... # return conservative sparsity pattern
 end

File: src/overloads/arrays.jl [hunk 5]
```diff
@@ -122,6 +122,19 @@ function LinearAlgebra.:\(
...
+    return inv(A) * B
+end
+
+function LinearAlgebra.:\(
+    A::AbstractMatrix{T1}, B::AbstractVecOrMat{T2}
+) where {T1<:AbstractTracer,T2<:AbstractTracer}
+    Ainv = LinearAlgebra.pinv(A)
+    return Ainv * B
+end
+
```
Comment (adrhill) [inline src/overloads/arrays.jl:137]: You probably just want to call `second_order_or` and return a `Fill` here.

Comment (ErikQQY) [reply src/overloads/arrays.jl:137]: I think this branch is something like `\(A::Abstract{<:AbstractTracer}, B::AbstractVecOrMat)` we defined before, the only difference is that here `B` is a matrix of gradient tracer right? Why don't we just directly use `pinv` here?

Comment (adrhill) [reply src/overloads/arrays.jl:134]: Because we can skip the entire computation and assume that the index sets inside of the tracers all get mixed!

Comment (adrhill) [reply src/overloads/arrays.jl:134]: I'm sorry, this is a bit of a non-trivial PR. I can probably find an hour tomorrow to push some changes.

Comment (ErikQQY) [reply src/overloads/arrays.jl]: Oh, I see. I changed to this dispatch to use `second_order_or` and `Fill` here.

**Comment by adrhill** [comment]
Minor revert due to https://github.com/domluna/JuliaFormatter.jl/issues/909.

**Comment by ErikQQY** [comment]
Awesome!!🚀
